/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectCreateRouteImport } from './routes/project/create'
import { Route as ProjectIdRouteImport } from './routes/project/$id'
import { Route as ProjectIdEditRouteImport } from './routes/project/$id.edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectCreateRoute = ProjectCreateRouteImport.update({
  id: '/project/create',
  path: '/project/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdEditRoute = ProjectIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/create': typeof ProjectCreateRoute
  '/project/$id/edit': typeof ProjectIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/create': typeof ProjectCreateRoute
  '/project/$id/edit': typeof ProjectIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/create': typeof ProjectCreateRoute
  '/project/$id/edit': typeof ProjectIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/profile'
    | '/project/$id'
    | '/project/create'
    | '/project/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile'
    | '/project/$id'
    | '/project/create'
    | '/project/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/profile'
    | '/project/$id'
    | '/project/create'
    | '/project/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProfileRoute: typeof ProfileRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
  ProjectCreateRoute: typeof ProjectCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/create': {
      id: '/project/create'
      path: '/project/create'
      fullPath: '/project/create'
      preLoaderRoute: typeof ProjectCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/edit': {
      id: '/project/$id/edit'
      path: '/edit'
      fullPath: '/project/$id/edit'
      preLoaderRoute: typeof ProjectIdEditRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdEditRoute: typeof ProjectIdEditRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdEditRoute: ProjectIdEditRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProfileRoute: ProfileRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
  ProjectCreateRoute: ProjectCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
